# Generated by Django 3.2.9 on 2021-11-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_costumer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='features/')),
                ('icon', models.FileField(upload_to='features/')),
                ('icon_background', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('testimonial_description', models.TextField(blank=True, null=True)),
                ('testimonial_author', models.CharField(max_length=255)),
                ('author_designation', models.CharField(max_length=255)),
                ('testimonial_logo', models.FileField(upload_to='features/')),
            ],
        ),
        migrations.AlterField(
            model_name='costumer',
            name='logo',
            field=models.FileField(upload_to='costumers/'),
        ),
    ]
