# Generated by Django 3.2.9 on 2021-11-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20211122_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='title',
            field=models.CharField(default='hnjm', max_length=255),
            preserve_default=False,
        ),
    ]
