# Generated by Django 3.2.9 on 2021-11-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_videoblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoblog',
            name='play',
            field=models.FileField(default='shyam', upload_to='videoBlog/'),
            preserve_default=False,
        ),
    ]
