# Generated by Django 3.2.9 on 2021-11-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='product/')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.TextField(blank=True, choices=[('blog_post', 'Blog Post'), ('webinar', 'Webinar'), ('project', 'Project')], max_length=255, null=True)),
            ],
        ),
    ]
