# Generated by Django 3.2.9 on 2021-11-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='white_logo',
            field=models.FileField(blank=True, null=True, upload_to='costumers/'),
        ),
    ]
