# Generated by Django 3.2.9 on 2021-11-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_costumer_white_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hero_image',
            field=models.FileField(default='shiyas', upload_to='product/hero_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='k', max_length=255),
            preserve_default=False,
        ),
    ]
