# Generated by Django 3.2.9 on 2021-11-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20211124_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='background_color',
            field=models.CharField(default='#ffc9b7', max_length=255),
            preserve_default=False,
        ),
    ]
